"""first_migration

Revision ID: b3a06c455c53
Revises: ec67b296dac1
Create Date: 2023-09-10 15:12:01.675099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3a06c455c53'
down_revision: Union[str, None] = 'ec67b296dac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advanced_analysis', sa.Column('entrada_id', sa.Integer(), nullable=True))
    op.add_column('advanced_analysis', sa.Column('resultado', sa.String(), nullable=True))
    op.drop_constraint('advanced_analysis_entry_id_fkey', 'advanced_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'advanced_analysis', 'entries', ['entrada_id'], ['id'])
    op.drop_column('advanced_analysis', 'entry_id')
    op.drop_column('advanced_analysis', 'result')
    op.add_column('customization', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('customization', sa.Column('emociones_rastreadas', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('customization', sa.Column('presentacion_datos', sa.String(), nullable=True))
    op.drop_constraint('customization_user_id_fkey', 'customization', type_='foreignkey')
    op.create_foreign_key(None, 'customization', 'users', ['usuario_id'], ['id'])
    op.drop_column('customization', 'user_id')
    op.add_column('emotion_history', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('emotion_history', sa.Column('emocion_id', sa.Integer(), nullable=True))
    op.add_column('emotion_history', sa.Column('fecha_hora', sa.DateTime(), nullable=True))
    op.add_column('emotion_history', sa.Column('intensidad', sa.Integer(), nullable=True))
    op.drop_constraint('emotion_history_emotion_id_fkey', 'emotion_history', type_='foreignkey')
    op.drop_constraint('emotion_history_user_id_fkey', 'emotion_history', type_='foreignkey')
    op.create_foreign_key(None, 'emotion_history', 'emotions', ['emocion_id'], ['id'])
    op.create_foreign_key(None, 'emotion_history', 'users', ['usuario_id'], ['id'])
    op.drop_column('emotion_history', 'timestamp')
    op.drop_column('emotion_history', 'emotion_id')
    op.drop_column('emotion_history', 'intensity')
    op.drop_column('emotion_history', 'user_id')
    op.add_column('entries', sa.Column('emotion_id', sa.Integer(), nullable=True))
    op.drop_constraint('entries_user_id_fkey', 'entries', type_='foreignkey')
    op.create_foreign_key(None, 'entries', 'emotions', ['emotion_id'], ['id'])
    op.drop_column('entries', 'user_id')
    op.add_column('entry_emotion', sa.Column('entrada_id', sa.Integer(), nullable=False))
    op.add_column('entry_emotion', sa.Column('emocion_id', sa.Integer(), nullable=False))
    op.add_column('entry_emotion', sa.Column('intensidad', sa.Integer(), nullable=True))
    op.drop_constraint('entry_emotion_entry_id_fkey', 'entry_emotion', type_='foreignkey')
    op.drop_constraint('entry_emotion_emotion_id_fkey', 'entry_emotion', type_='foreignkey')
    op.create_foreign_key(None, 'entry_emotion', 'emotions', ['emocion_id'], ['id'])
    op.create_foreign_key(None, 'entry_emotion', 'entries', ['entrada_id'], ['id'])
    op.drop_column('entry_emotion', 'emotion_id')
    op.drop_column('entry_emotion', 'intensity')
    op.drop_column('entry_emotion', 'entry_id')
    op.add_column('notifications', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('mensaje', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('fecha_hora', sa.DateTime(), nullable=True))
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['usuario_id'], ['id'])
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'user_id')
    op.drop_column('notifications', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_column('notifications', 'fecha_hora')
    op.drop_column('notifications', 'mensaje')
    op.drop_column('notifications', 'usuario_id')
    op.add_column('entry_emotion', sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('entry_emotion', sa.Column('intensity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('entry_emotion', sa.Column('emotion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'entry_emotion', type_='foreignkey')
    op.drop_constraint(None, 'entry_emotion', type_='foreignkey')
    op.create_foreign_key('entry_emotion_emotion_id_fkey', 'entry_emotion', 'emotions', ['emotion_id'], ['id'])
    op.create_foreign_key('entry_emotion_entry_id_fkey', 'entry_emotion', 'entries', ['entry_id'], ['id'])
    op.drop_column('entry_emotion', 'intensidad')
    op.drop_column('entry_emotion', 'emocion_id')
    op.drop_column('entry_emotion', 'entrada_id')
    op.add_column('entries', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.create_foreign_key('entries_user_id_fkey', 'entries', 'users', ['user_id'], ['id'])
    op.drop_column('entries', 'emotion_id')
    op.add_column('emotion_history', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('emotion_history', sa.Column('intensity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('emotion_history', sa.Column('emotion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('emotion_history', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'emotion_history', type_='foreignkey')
    op.drop_constraint(None, 'emotion_history', type_='foreignkey')
    op.create_foreign_key('emotion_history_user_id_fkey', 'emotion_history', 'users', ['user_id'], ['id'])
    op.create_foreign_key('emotion_history_emotion_id_fkey', 'emotion_history', 'emotions', ['emotion_id'], ['id'])
    op.drop_column('emotion_history', 'intensidad')
    op.drop_column('emotion_history', 'fecha_hora')
    op.drop_column('emotion_history', 'emocion_id')
    op.drop_column('emotion_history', 'usuario_id')
    op.add_column('customization', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customization', type_='foreignkey')
    op.create_foreign_key('customization_user_id_fkey', 'customization', 'users', ['user_id'], ['id'])
    op.drop_column('customization', 'presentacion_datos')
    op.drop_column('customization', 'emociones_rastreadas')
    op.drop_column('customization', 'usuario_id')
    op.add_column('advanced_analysis', sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('advanced_analysis', sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'advanced_analysis', type_='foreignkey')
    op.create_foreign_key('advanced_analysis_entry_id_fkey', 'advanced_analysis', 'entries', ['entry_id'], ['id'])
    op.drop_column('advanced_analysis', 'resultado')
    op.drop_column('advanced_analysis', 'entrada_id')
    # ### end Alembic commands ###
